= Chapter3
Firstname Lastname <author@asciidoctor.org>
3.0, July 29, 2022: AsciiDoc article template
:toc:
:icons: font
:url-quickref: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/


== 1.배열의 기본 유형 은 무엇을 의미합니까 ?
.배열
====
배열이 가지고있는 타입
====

== 2.다음 가변성 방법의 목적은 무엇입니까? same(1,2,3) , same(17,17,17,17) 및 same(2) 의 값은 무엇입니까 ? 왜?
.코드
----
static double same( int... value ) {
    for (int i = 1; i < value.length; i++) {
        if ( value[i-1] != value[i] )
            return false;
    }
    return true;
}
----
====
false true true
1 ,2, 3 다름
같음
크기가 1이라 조건에 안들어감
====

== 3.배열을 정렬한다는 것은 무엇을 의미합니까?
====
serach하기 쉽게 정리해두는
====

== 4.선형 검색에 비해 이진 검색의 주요 장점은 무엇입니까? 주요 단점은 무엇입니까?
.장단점
====
이진 탐색이 매우 빠르지만 정렬이 되어잇어야함.
====

== 5.동적 배열 이란 무엇을 의미합니까 ? 일반 배열에 비해 동적 배열의 장점은 무엇입니까?

. 동적배열이란?
====
런타임에 배열의 크기를 정하는것, 늘렸다 줄였다 할수잇다.
====

== 6. ArrayList가 매개변수화된 유형이라는 것은 무엇을 의미합니까 ?
====
T처럼 다양한게 들어갈수잇는것
====



== 7. 변수 strlst가 다음과 같이 선언되었다고 가정합니다. \n ArrayList<String> strlst = new ArrayList<String>();목록이 비어 있지 않고 목록의 모든 항목이 null이 아니라고 가정합니다. 목록에서 사전순으로 가장 먼저 나오는 문자열을 찾아서 인쇄하는 코드 세그먼트를 작성하세요.
.code
[source,java]
----
String smallest = strlst.get(0);
for (String item : strlst) {
   if ( item.compareTo(smallest) < 0 )
       smallest = item;
}
System.out.println("The smallest string lexicographically is " + smallest)
----


== 8.다음 코드 세그먼트에서 생성된 정확한 출력을 보여줍니다.


.code
[source,java]
----
char[][] pic = new char[6][6];
for (int i = 0; i < 6; i++)
   for (int j = 0; j < 6; j++) {
      if ( i == j  ||  i == 0  ||  i == 5 )
         pic[i][j] = '*';
      else
         pic[i][j] = '.';
   }
for (int i = 0; i < 6; i++) {
   for (int j = 0; j < 6; j++)
      System.out.print(pic[i][j]);
   System.out.println();
}
}
----
====
******
.*....
..*...
...*..
....*.
******
====
====
pic[0][0] pic[0][1] pic[0][2] pic[0][3] pic[0][4] pic[0][5]
pic[1][0] pic[1][1] pic[1][2] pic[1][3] pic[1][4] pic[1][5]
pic[2][0] pic[2][1] pic[2][2] pic[2][3] pic[2][4] pic[2][5]
pic[3][0] pic[3][1] pic[3][2] pic[3][3] pic[3][4] pic[3][5]
pic[4][0] pic[4][1] pic[4][2] pic[4][3] pic[4][4] pic[4][5]
pic[5][0] pic[5][1] pic[5][2] pic[5][3] pic[5][4] pic[5][5]
====

== 9. 1부터 10까지의 범위에서 선택된 두 개의 서로 다른 임의의 정수를 인쇄하는 코드 세그먼트를 작성하세요. 가능한 모든 출력은 동일한 확률을 가져야 합니다. 힌트: 두 개의 임의의 숫자를 쉽게 선택할 수 있지만 선택한 두 숫자가 동일할 수도 있다는 사실을 고려해야 합니다..프레임
.code
[source,java]
----
int x,y;
do {
    x = (int)(10*Math.random() + 1);
    y = (int)(10*Math.random() + 1);
} while (x == y);
System.out.println(x +""+ y);
----


== 10.s1 및 s2 가 String 유형의 변수이고 해당 값이 int 유형 값의 문자열 표현일 것으로 예상된다고 가정합니다 . 해당 값의 정수 합계를 계산하고 인쇄하거나 값을 정수로 성공적으로 변환할 수 없는 경우 오류 메시지를 인쇄하는 코드 세그먼트를 작성하세요. ( try..catch 문을 사용하세요.).프레임
.code
[source,java]
----
String s1 = "194";
String s2 = "103";
try{
    Integer.parseInt(s1);
    Intger.parseInt(s2);

}catch(NumberFormatException e )
{
    log.info(e.toString);
}
----


== 11.Show the exact output that would be produced by the following main() routine:
[source,java]
----
public static void main(String[] args) {
    int N;
    N = 1;
    while (N <= 32) {
        N = 2 * N;
        System.out.println(N);
    }
}
----

.reslut
====
2
4
8
16
32
64
====


== 12. Show the exact output produced by the following main() routine:
[source,java]
----
public static void main(String[] args) {
    int x,y;
    x = 5;
    y = 1;
    while (x > 0) {
        x = x - 1;
        y = y * x;
        System.out.println(y);
    }
}
----

.reslut
[source]
----
4
12
24
24
0
----

== 13. What output is produced by the following program segment? Why? (Recall that name.charAt(i) is the i-th character in the string, name.)
[source,java]
----
String name;
int i;
boolean startWord;
name = "Richard M. Nixon";
startWord = true;
for (i = 0; i < name.length(); i++) {
    if (startWord)
        System.out.println(name.charAt(i));
    if (name.charAt(i) == ' ')
        startWord = true;
    else
        startWord = false;
}
----

.reslut
[source]
---
R
M
N
//빈공백뒤 만 true고 초기값도 true이기 떄문에
---


== 14.다음 서브루틴의 목적은 무엇입니까? 매개변수 값 측면에서 반환되는 값의 의미는 무엇입니까?



.code
[source,java]
----
static double[] sums( double[][] data ) {
    double[] answers = new double[ data.length ];
    for (int i = 0; i < data.length; i++) {
        double sum = 0;
        for (int j = 0; j < data[i].length; i++)
            sum = sum + data[i][j];
        answers[i] = sum;
    }
    return answers;
}
----
====
서브루틴의 목적은 매개변수 배열 데이터 의 각 행에 있는 숫자의 합을 찾는 것입

====




Question 3:

What does it mean to sort an array?

배열을 정렬한다는 의미는 오름차순 or 내림차순 or 특정한 기준을 가지고
배열의 요소들을 재배치 하겠다는 의미입니다.


Question 4:

What is the main advantage of binary search over linear search?
What is the main disadvantage?

일단 이진탐색은 매우 빠릅니다 선형탐색은 O(N)이 필요하지만
이진탐색의 경우 O(longN)시간만 있으면 됩니다.

하지만 이진탐색을 하기 위해서는 정렬이 되있는 상태여야 합니다.



Question 5:

What is meant by a dynamic array? What is the advantage of a dynamic array over a regular array?

다이나믹 어레이는 , 배열의 크기가 동적인 배열을 의미합니다.
자바에서는 List<Integer>ArrayList 로 만들어지고
이는 동적인 배열을 의미합니다.

동적인 배열의 장점은 정해진 크기가 없기 떄문에 , 값을 계속해서 받아도 문제가 없습니다.


Question 6:

What does it mean to say that ArrayList is a parameterized type?

ArrayList는 parameterized type인데 , 이는 Generic한 방식으로 구현됐음을 의미합니다.

자바에서 Generic은 <T>타입으로 명시되있는것을 의미하는데
<T>는 타입이 아직 정해지지 않았음을 의미합니다.

이 <T>에는 primitive type은 올 수 없으며 , Object가 와야 합니다.
그렇기 떄문에 int 는 올 수 없고 Interger 는 올 수 있습니다

Question 7:

Suppose that a variable strlst has been declared as

ArrayList<String> strlst = new ArrayList<String>();
Assume that the list is not empty and that all the items in the list are non-null.
Write a code segment that will find and print the string in the list that comes
first in lexicographic order.

Collections.sort(strlst);
sout(strlst.get(0));



Question 8:

Show the exact output produced by the following code segment.

char[][] pic = new char[6][6];
for (int i = 0; i < 6; i++)
   for (int j = 0; j < 6; j++) {
      if ( i == j  ||  i == 0  ||  i == 5 )
         pic[i][j] = '*';
      else
         pic[i][j] = '.';
   }

for (int i = 0; i < 6; i++) {
   for (int j = 0; j < 6; j++)
      System.out.print(pic[i][j]);
   System.out.println();
}



******
.*....
..*...
...*..
....*.
******



Question 9:

Write a complete static method that finds the largest value in an array of ints.
The method should have one parameter, which is an array of type int[].
The largest number in the array should be returned as the value of the method.


static findMax(in[]arr){
   int max=arr[0];
   for(int i=1;i<arr.length;i++)
	max=Math.max(max,arr[i]);
return max;
}




Question 10:

Suppose that temperature measurements were made on each day of 2021 in each of 100 cities.
The measurements have been stored in an array

int[][]  temps  =  new  int[100][365];
where temps[c][d] holds the measurement for city number c on the dth day of the year.
Write a code segment that will print out the average temperature,
over the course of the whole year, for each city.
The average temperature for a city can be obtained by adding up all 365 measurements
for that city and dividing the answer by 365.0.


for(int i=0;i<100;i++){
	doublesum=0;
	for(int j=0;j<365;j++){
		sum+=arr[i][j];
	}
	sout(sum/365.0);
}


Suppose that a class, Employee, is defined as follows:

class Employee {
   String lastName;
   String firstName;
   double hourlyWage;
   int yearsWithCompany;
}
Suppose that data about 100 employees is already stored in an array:

Employee[] employeeData = new Employee[100];
Write a code segment that will output the first name, last name,
 and hourly wage of each employee who has been with the company for 20 years or more.
Write two versions of the code segment, one that uses a regular for loop,
and one that uses a for-each loop.


for(int i=0;i<100;i++){
	if(employeeData [i].yearsWithCompany>=20)
		sout()
}

for(employee: employeeData){
	if(employee.yearsWithCompany>=20)
		sout();
}

질문 12, 13은 record에 관한 내용
이건 자바14에서부터 나오기 떄문에 넘기겠


Question 14:
